/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "Auth.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TokenRequest, TokenRequest, AUTO)


PB_BIND(TokenResponse, TokenResponse, 2)



