// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ELData.proto
// Protobuf C++ Version: 4.26.0-dev

#ifndef GOOGLE_PROTOBUF_INCLUDED_ELData_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_ELData_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 4026000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ELData_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ELData_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ELData_2eproto;
class ELData;
struct ELDataDefaultTypeInternal;
extern ELDataDefaultTypeInternal _ELData_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ELData final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ELData) */ {
 public:
  inline ELData() : ELData(nullptr) {}
  ~ELData() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ELData(
      ::google::protobuf::internal::ConstantInitialized);

  inline ELData(const ELData& from) : ELData(nullptr, from) {}
  inline ELData(ELData&& from) noexcept
      : ELData(nullptr, std::move(from)) {}
  inline ELData& operator=(const ELData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ELData& operator=(ELData&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ELData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ELData* internal_default_instance() {
    return reinterpret_cast<const ELData*>(
        &_ELData_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ELData& a, ELData& b) { a.Swap(&b); }
  inline void Swap(ELData* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ELData* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ELData* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ELData>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ELData& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ELData& from) { ELData::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ELData* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "ELData"; }

 protected:
  explicit ELData(::google::protobuf::Arena* arena);
  ELData(::google::protobuf::Arena* arena, const ELData& from);
  ELData(::google::protobuf::Arena* arena, ELData&& from) noexcept
      : ELData(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSensorIdFieldNumber = 1,
    kSensorValueFieldNumber = 2,
  };
  // string sensorId = 1;
  void clear_sensorid() ;
  const std::string& sensorid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sensorid(Arg_&& arg, Args_... args);
  std::string* mutable_sensorid();
  PROTOBUF_NODISCARD std::string* release_sensorid();
  void set_allocated_sensorid(std::string* value);

  private:
  const std::string& _internal_sensorid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sensorid(
      const std::string& value);
  std::string* _internal_mutable_sensorid();

  public:
  // float sensorValue = 2;
  void clear_sensorvalue() ;
  float sensorvalue() const;
  void set_sensorvalue(float value);

  private:
  float _internal_sensorvalue() const;
  void _internal_set_sensorvalue(float value);

  public:
  // @@protoc_insertion_point(class_scope:ELData)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      23, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr sensorid_;
    float sensorvalue_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ELData_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ELData

// string sensorId = 1;
inline void ELData::clear_sensorid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sensorid_.ClearToEmpty();
}
inline const std::string& ELData::sensorid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ELData.sensorId)
  return _internal_sensorid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ELData::set_sensorid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sensorid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ELData.sensorId)
}
inline std::string* ELData::mutable_sensorid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sensorid();
  // @@protoc_insertion_point(field_mutable:ELData.sensorId)
  return _s;
}
inline const std::string& ELData::_internal_sensorid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.sensorid_.Get();
}
inline void ELData::_internal_set_sensorid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sensorid_.Set(value, GetArena());
}
inline std::string* ELData::_internal_mutable_sensorid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.sensorid_.Mutable( GetArena());
}
inline std::string* ELData::release_sensorid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:ELData.sensorId)
  return _impl_.sensorid_.Release();
}
inline void ELData::set_allocated_sensorid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sensorid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.sensorid_.IsDefault()) {
          _impl_.sensorid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ELData.sensorId)
}

// float sensorValue = 2;
inline void ELData::clear_sensorvalue() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sensorvalue_ = 0;
}
inline float ELData::sensorvalue() const {
  // @@protoc_insertion_point(field_get:ELData.sensorValue)
  return _internal_sensorvalue();
}
inline void ELData::set_sensorvalue(float value) {
  _internal_set_sensorvalue(value);
  // @@protoc_insertion_point(field_set:ELData.sensorValue)
}
inline float ELData::_internal_sensorvalue() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.sensorvalue_;
}
inline void ELData::_internal_set_sensorvalue(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.sensorvalue_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_ELData_2eproto_2epb_2eh
