name: Build c

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        required: true

jobs:
  build-c:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "27.x"

      - name: Install Nanopb
        run: | 
          pip install --upgrade protobuf grpcio-tools
          mkdir -p nanopb
          curl -L https://jpa.kapsi.fi/nanopb/download/nanopb-0.4.8-linux-x86.tar.gz | tar xz -C nanopb --strip-components=1

      - name: Make c release
        run: |
          cd build/c
          make

      - name: Upload c assets to release
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release upload ${{ github.event.inputs.tag }} release/c_build.zip
